import {
  默认关键词颜色,
  默认内置字词颜色,
  默认奇偶行颜色,
  默认引文背景色,
  默认页面背景色,
  默认纸面色,
  自动滚动默认速度,
  默认字号,
} from './常量.js';

export const 字体设置 = { 引号内: null, 引号外: null };
export const 字体粗细设置 = { 引号内: null, 引号外: null };
export const 字体颜色设置 = { 引号内: null, 引号外: null };
export const 奇偶行颜色 = { ...默认奇偶行颜色 };
export const 引文背景色 = { ...默认引文背景色 };
export const 外观 = {
  关键词颜色: 默认关键词颜色,
  内置字词颜色: 默认内置字词颜色,
  关键词粗细: null,
  页面背景色: 默认页面背景色,
  纸面色: 默认纸面色,
  引文背景色启用: true,
  引文边框启用: true,
  // 折行句竖条：同一句话折成多行时行首留白里的相连竖条
  换行标记启用: true,
  // 阶梯段落：句内停顿处断行并逐级缩进（仅排版层，不修改文本本身）
  阶梯段落启用: false,
  当前字体标签: '引号内',
};
export const 统计 = {
  // 自动滚动时长统计：今日总时长及按书分项按本地日期归零；每本书另存历史累计。
  今日滚动日期: '',
  今日滚动毫秒: 0,
  今日书籍滚动毫秒: new Map(),
  书籍滚动毫秒: new Map(),
  未入账滚动毫秒: 0, // 滚动会话中已累计、待结转到统计的毫秒数
};

export const 状态 = {
  文本: '',
  文件名: '',
  行起点列表: new Uint32Array(),
  行终点列表: new Uint32Array(),
  行逻辑索引: new Uint32Array(),
  行段落索引: new Uint32Array(),
  行阶梯索引: null,
  阶梯断点: null,
  引文边界列表: new Uint32Array(),
  缩进起点集合: new Set(),
  排版键: '',
  行高: 39,
  渲染起点: -1,
  渲染终点: -1,
  滚动帧: 0,
  滚动动画帧: 0,
  滚动动画目标: null,
  尺寸计时器: 0,
  保存计时器: 0,
  迸发计时器: 0,
  衔接线计时器: 0,
  载入序号: 0,
  排版任务序号: 0,
  拖选状态: null,
  关键词列表: [],
  当前关键词id: null,
  悬停关键词id: null,
  悬停命中idx: null,
  正文悬停已暂停: false,
  下一个关键词id: 1,
  跳转起点: null,
  查找临时关键词id: null,
  指示器缓存: null,
  当前命中位置计时器: 0,
  关键词面板展开: false,
  关键词面板签名: '',
  关键词排序: '数量',
  上下文视图: null,
  自动滚动速度: 自动滚动默认速度,
  句段起点列表: new Uint32Array(), // 全文「无标点连续段」起点（文本偏移，升序），用于运行时二分
  句段负担前缀和: new Float64Array(1), // 句段负担前缀和，长度 = 段数 + 1；[i] = 前 i 段负担之和
  句段负担总合: 0, // 全部句段负担之和（= 前缀和末位），用于剩余时间语义化
  全文负担密度: 0, // 负担/像素 = 句段负担总合 ÷ 虚拟总高度；视口期望负担 = 密度 × 视口高度
  字号: 默认字号,
  词频分析: null,
  全文单字: new Set(),
  文本目录: [],
  文本字数: new Map(),
};

export const 元素 = {
  滚动容器: document.querySelector('#滚动容器'),
  虚拟画布: document.querySelector('#虚拟画布'),
  可见内容: document.querySelector('#可见内容'),
  载入状态: document.querySelector('#载入状态'),
  跳转边框: document.querySelector('#跳转边框'),
  跳转迸发: document.querySelector('#跳转迸发'),
  衔接线: document.querySelector('#衔接线'),
  查找弹窗: document.querySelector('#查找弹窗'),
  查找表单: document.querySelector('#查找表单'),
  查找输入框: document.querySelector('#查找输入框'),
  查找反馈: document.querySelector('#查找反馈'),
  查找命中摘要: document.querySelector('#查找命中摘要'),
  查找上一个按钮: document.querySelector('#查找上一个按钮'),
  查找下一个按钮: document.querySelector('#查找下一个按钮'),
  分析结果: document.querySelector('#分析结果'),
  分析结果摘要: document.querySelector('#分析结果摘要'),
  分析分栏: document.querySelector('.分析分栏'),
  前置词组列表: document.querySelector('#前置词组列表'),
  后续词组列表: document.querySelector('#后续词组列表'),
  关闭查找按钮: document.querySelector('#关闭查找按钮'),
  自定义滚动条: document.querySelector('#自定义滚动条'),
  滚动块: document.querySelector('#滚动块'),
  滚动进度: document.querySelector('#滚动进度'),
  滚动百分比: document.querySelector('#滚动百分比'),
  剩余滚动时间行: document.querySelector('#剩余滚动时间行'),
  剩余滚动时间: document.querySelector('#剩余滚动时间'),
  本书滚动时间: document.querySelector('#本书滚动时间'),
  已滚动时间行: document.querySelector('#已滚动时间行'),
  已滚动时间: document.querySelector('#已滚动时间'),
  今日滚动时间: document.querySelector('#今日滚动时间'),
  基础速度显示: document.querySelector('#基础速度显示'),
  实际速度显示: document.querySelector('#实际速度显示'),
  关键词指示器: document.querySelector('#关键词指示器'),
  悬停关键词指示器: document.querySelector('#悬停关键词指示器'),
  自动滚动按钮: document.querySelector('#自动滚动按钮'),
  当前时间: document.querySelector('#当前时间'),
  字号控制: document.querySelector('#字号控制'),
  字号值: document.querySelector('#字号值'),
  行距控制: document.querySelector('#行距控制'),
  行距值: document.querySelector('#行距值'),
  内容选择按钮: document.querySelector('#内容选择按钮'),
  内容选择弹窗: document.querySelector('#内容选择弹窗'),
  内容选择摘要: document.querySelector('#内容选择摘要'),
  内容选择列表: document.querySelector('#内容选择列表'),
  关闭内容选择按钮: document.querySelector('#关闭内容选择按钮'),
  关键词面板: document.querySelector('#关键词面板'),
  关键词面板开关: document.querySelector('#关键词面板开关'),
  关键词列表容器: document.querySelector('#关键词列表容器'),
  上下文弹窗: document.querySelector('#上下文弹窗'),
  上下文标题: document.querySelector('#上下文标题'),
  上下文列表: document.querySelector('#上下文列表'),
  关闭上下文按钮: document.querySelector('#关闭上下文按钮'),
  词频弹窗: document.querySelector('#词频弹窗'),
  词频摘要: document.querySelector('#词频摘要'),
  词频标签栏: document.querySelector('#词频标签栏'),
  单字双列表: document.querySelector('#单字双列表'),
  单字重复列表: document.querySelector('#单字重复列表'),
  单字一次列表: document.querySelector('#单字一次列表'),
  词频表格容器: document.querySelector('#词频表格容器'),
  词频列表: document.querySelector('#词频列表'),
  词频分页: document.querySelector('#词频分页'),
  词频上一页: document.querySelector('#词频上一页'),
  词频页码: document.querySelector('#词频页码'),
  词频下一页: document.querySelector('#词频下一页'),
  关闭词频按钮: document.querySelector('#关闭词频按钮'),
  字体弹窗: document.querySelector('#字体弹窗'),
  字体遮罩: document.querySelector('#字体遮罩'),
  关闭字体按钮: document.querySelector('#关闭字体按钮'),
  字体重置按钮: document.querySelector('#字体重置按钮'),
  字体关闭底部按钮: document.querySelector('#字体关闭底部按钮'),
  字体标签引号内: document.querySelector('#字体标签引号内'),
  字体标签引号外: document.querySelector('#字体标签引号外'),
  字体标签全部: document.querySelector('#字体标签全部'),
  字体标签关键词: document.querySelector('#字体标签关键词'),
  字体标签背景: document.querySelector('#字体标签背景'),
  引文背景色选项: document.querySelector('#引文背景色选项'),
  引文背景色开关: document.querySelector('#引文背景色开关'),
  奇数引文颜色选择器: document.querySelector('#奇数引文颜色选择器'),
  偶数引文颜色选择器: document.querySelector('#偶数引文颜色选择器'),
  引文边框选项: document.querySelector('#引文边框选项'),
  引文边框开关: document.querySelector('#引文边框开关'),
  阶梯段落选项: document.querySelector('#阶梯段落选项'),
  阶梯段落开关: document.querySelector('#阶梯段落开关'),
  换行标记选项: document.querySelector('#换行标记选项'),
  换行标记开关: document.querySelector('#换行标记开关'),
  关键词颜色选项: document.querySelector('#关键词颜色选项'),
  关键词颜色选择器: document.querySelector('#关键词颜色选择器'),
  字体颜色选项: document.querySelector('#字体颜色选项'),
  字体颜色选择器: document.querySelector('#字体颜色选择器'),
  内置字词颜色选项: document.querySelector('#内置字词颜色选项'),
  内置字词颜色选择器: document.querySelector('#内置字词颜色选择器'),
  奇偶行颜色选项: document.querySelector('#奇偶行颜色选项'),
  奇数行颜色选择器: document.querySelector('#奇数行颜色选择器'),
  偶数行颜色选择器: document.querySelector('#偶数行颜色选择器'),
  背景颜色选项: document.querySelector('#背景颜色选项'),
  背景色选择器: document.querySelector('#背景色选择器'),
  字体粗细按钮: document.querySelector('#字体粗细按钮'),
  字体选项列表: document.querySelector('#字体选项列表'),
};
